source 'https://github.com/CocoaPods/Specs.git'

target 'RMPZoomTransitionAnimator' do
  pod "RMPZoomTransitionAnimator", :path => "../"
end

target 'Tests' do
  inherit! :search_paths

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
